-- HandheldAtlas Phase 6
-- Game ratings, anti-abuse guardrails and monthly Community Top 5.

create table if not exists public.game_ratings (
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (game_id, user_id)
);

alter table public.game_ratings
add column if not exists created_at timestamptz not null default now();

alter table public.game_ratings
add column if not exists updated_at timestamptz not null default now();

alter table public.game_ratings
drop constraint if exists game_ratings_rating_check;

alter table public.game_ratings
add constraint game_ratings_rating_check
check (rating between 1 and 5);

create unique index if not exists game_ratings_game_user_uidx
on public.game_ratings(game_id, user_id);

create index if not exists game_ratings_game_idx
on public.game_ratings(game_id);

create index if not exists game_ratings_updated_idx
on public.game_ratings(updated_at desc);

create table if not exists public.game_rating_monthly (
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating_month date not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (game_id, user_id, rating_month),
  constraint game_rating_monthly_month_start_check
  check (rating_month = date_trunc('month', rating_month::timestamp)::date)
);

create index if not exists game_rating_monthly_month_game_idx
on public.game_rating_monthly(rating_month, game_id);

create table if not exists public.game_rating_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null check (action in ('set', 'remove')),
  rating smallint null check (rating is null or rating between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists game_rating_events_user_time_idx
on public.game_rating_events(user_id, created_at desc);

create index if not exists game_rating_events_game_time_idx
on public.game_rating_events(game_id, created_at desc);

-- Preserve ratings already cast during the current UTC month.
insert into public.game_rating_monthly (
  game_id,
  user_id,
  rating_month,
  rating,
  created_at,
  updated_at
)
select
  game_id,
  user_id,
  date_trunc('month', updated_at at time zone 'utc')::date,
  rating,
  created_at,
  updated_at
from public.game_ratings
where updated_at >= date_trunc('month', now() at time zone 'utc')
on conflict (game_id, user_id, rating_month)
do update set
  rating = excluded.rating,
  updated_at = excluded.updated_at;

grant select, insert, update, delete
on public.game_ratings
to authenticated;

grant select
on public.game_rating_monthly
to authenticated;

grant select
on public.game_rating_events
to authenticated;

alter table public.game_ratings enable row level security;
alter table public.game_rating_monthly enable row level security;
alter table public.game_rating_events enable row level security;

drop policy if exists "Users can read their own game ratings"
on public.game_ratings;

create policy "Users can read their own game ratings"
on public.game_ratings
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert their own game ratings"
on public.game_ratings;

create policy "Users can insert their own game ratings"
on public.game_ratings
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update their own game ratings"
on public.game_ratings;

create policy "Users can update their own game ratings"
on public.game_ratings
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can delete their own game ratings"
on public.game_ratings;

create policy "Users can delete their own game ratings"
on public.game_ratings
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can read their own monthly game ratings"
on public.game_rating_monthly;

create policy "Users can read their own monthly game ratings"
on public.game_rating_monthly
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Staff can read game rating events"
on public.game_rating_events;

create policy "Staff can read game rating events"
on public.game_rating_events
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('moderator', 'atlas_editor', 'admin')
  )
);

create or replace function public.set_game_rating(
  p_game_id uuid,
  p_rating smallint default null
)
returns table (
  average_rating numeric,
  rating_count bigint,
  user_rating smallint,
  monthly_rating_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_month date := date_trunc('month', now() at time zone 'utc')::date;
  v_recent_actions integer;
begin
  if v_actor is null then
    raise exception 'Authentication required';
  end if;

  if p_rating is not null and (p_rating < 1 or p_rating > 5) then
    raise exception 'Rating must be a whole number from 1 to 5';
  end if;

  if not exists (
    select 1
    from public.games
    where games.id = p_game_id
      and games.status = 'published'
  ) then
    raise exception 'This game is not available for rating';
  end if;

  select count(*)::integer
  into v_recent_actions
  from public.game_rating_events
  where user_id = v_actor
    and created_at >= now() - interval '1 hour';

  if v_recent_actions >= 30 then
    raise exception 'Too many rating changes. Please try again later.';
  end if;

  if p_rating is null then
    delete from public.game_ratings
    where game_id = p_game_id
      and user_id = v_actor;

    delete from public.game_rating_monthly
    where game_id = p_game_id
      and user_id = v_actor
      and rating_month = v_month;

    insert into public.game_rating_events (
      game_id,
      user_id,
      action,
      rating
    ) values (
      p_game_id,
      v_actor,
      'remove',
      null
    );
  else
    insert into public.game_ratings (
      game_id,
      user_id,
      rating,
      created_at,
      updated_at
    ) values (
      p_game_id,
      v_actor,
      p_rating,
      now(),
      now()
    )
    on conflict (game_id, user_id)
    do update set
      rating = excluded.rating,
      updated_at = now();

    insert into public.game_rating_monthly (
      game_id,
      user_id,
      rating_month,
      rating,
      created_at,
      updated_at
    ) values (
      p_game_id,
      v_actor,
      v_month,
      p_rating,
      now(),
      now()
    )
    on conflict (game_id, user_id, rating_month)
    do update set
      rating = excluded.rating,
      updated_at = now();

    insert into public.game_rating_events (
      game_id,
      user_id,
      action,
      rating
    ) values (
      p_game_id,
      v_actor,
      'set',
      p_rating
    );
  end if;

  return query
  select
    round(avg(game_ratings.rating)::numeric, 2),
    count(*)::bigint,
    max(
      case
        when game_ratings.user_id = v_actor then game_ratings.rating
        else null
      end
    )::smallint,
    (
      select count(*)::bigint
      from public.game_rating_monthly
      where game_rating_monthly.game_id = p_game_id
        and game_rating_monthly.rating_month = v_month
    )
  from public.game_ratings
  where game_ratings.game_id = p_game_id;
end;
$$;

create or replace function public.get_game_rating_summary(
  p_game_id uuid
)
returns table (
  average_rating numeric,
  rating_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    round(avg(game_ratings.rating)::numeric, 2) as average_rating,
    count(*)::bigint as rating_count
  from public.game_ratings
  where game_ratings.game_id = p_game_id;
$$;

create or replace function public.get_game_rating_summaries()
returns table (
  game_id uuid,
  average_rating numeric,
  rating_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    game_ratings.game_id,
    round(avg(game_ratings.rating)::numeric, 2) as average_rating,
    count(*)::bigint as rating_count
  from public.game_ratings
  join public.games
    on games.id = game_ratings.game_id
  where games.status = 'published'
  group by game_ratings.game_id;
$$;

create or replace function public.get_monthly_top_games(
  p_month_start date default date_trunc('month', now() at time zone 'utc')::date,
  p_limit integer default 5,
  p_min_votes integer default 3
)
returns table (
  game_id uuid,
  name text,
  slug text,
  genre text,
  atlas_score integer,
  cover_image_url text,
  average_rating numeric,
  rating_count bigint,
  weighted_score numeric
)
language sql
stable
security definer
set search_path = public
as $$
  with monthly_scores as (
    select
      game_rating_monthly.game_id,
      avg(game_rating_monthly.rating)::numeric as average_rating,
      count(*)::bigint as rating_count,
      (
        sum(game_rating_monthly.rating)::numeric + (3.5 * 5)
      ) / (
        count(*)::numeric + 5
      ) as weighted_score
    from public.game_rating_monthly
    where game_rating_monthly.rating_month = date_trunc('month', p_month_start::timestamp)::date
    group by game_rating_monthly.game_id
    having count(*) >= greatest(p_min_votes, 1)
  )
  select
    games.id as game_id,
    games.name::text,
    games.slug::text,
    games.genre::text,
    games.atlas_score::integer,
    games.cover_image_url::text,
    round(monthly_scores.average_rating, 2) as average_rating,
    monthly_scores.rating_count,
    round(monthly_scores.weighted_score, 4) as weighted_score
  from monthly_scores
  join public.games
    on games.id = monthly_scores.game_id
  where games.status = 'published'
  order by
    monthly_scores.weighted_score desc,
    monthly_scores.rating_count desc,
    games.atlas_score desc nulls last,
    games.name asc
  limit least(greatest(p_limit, 1), 20);
$$;

revoke all on function public.set_game_rating(uuid, smallint) from public;
grant execute on function public.set_game_rating(uuid, smallint) to authenticated;

grant execute on function public.get_game_rating_summary(uuid) to anon, authenticated;
grant execute on function public.get_game_rating_summaries() to anon, authenticated;
grant execute on function public.get_monthly_top_games(date, integer, integer) to anon, authenticated;
